### ISSUE TITLE
delegate-to and delegate-from are mixed up

### ISSUE THREAD

**Issue by Elan0r** [AlmondOffSec/PassTheCert#1]
At First: Awesome Work, THX, i like it!

when using -action write_rbcd the delegate-from and delegate-to parameters are mixed up logically.

It should be delegate-from 'dc$' delegate-to 'PC$'

![mixed1](https://user-images.githubusercontent.com/85351442/167129064-e4786159-b715-4348-935e-07c9d53ac74f.png)

![mixed2](https://user-images.githubusercontent.com/85351442/167129066-7d08fae6-294e-4ab3-af72-1241c22cafb0.png)

**Comment by Updates2023** [comment]
[Hi,](url) 
Could you help me please?


![image](https://user-images.githubusercontent.com/40759464/167132027-27e61e9f-ea86-4235-846f-c82cd94265de.png)

i got the following error:
[+] Impacket Library Installation Path: /usr/local/lib/python3.9/dist-packages/impacket-0.10.1.dev1+20220504.120002.d5097759-py3.9.egg/impacket
Traceback (most recent call last):
  File "/home/parrot/CRTO/tools/pywhisker/pass.py", line 479, in <module>
    ldapConn = ldap3.Connection(ldapServer, **ldap_connection_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ldap3-2.9.1-py3.9.egg/ldap3/core/connection.py", line 363, in __init__
    self._do_auto_bind()
  File "/usr/local/lib/python3.9/dist-packages/ldap3-2.9.1-py3.9.egg/ldap3/core/connection.py", line 412, in _do_auto_bind
    raise LDAPBindError(error)
ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials
automatic bind not successful - invalidCredentials

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello @Elan0r,
Thanks for the feedback :wink: 

Regarding your question, to be honest, I've just copy-pasted code from [rbcd.py](https://github.com/SecureAuthCorp/impacket/blob/master/examples/rbcd.py) but I don't think is messed up because the delegation is performed **from** `PC$` and you allow delegation right **to** `DC01$`.

Cheers,

:sunflower:

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello @itayyashar,

The error message is pretty simple: the provided credentials are not valid. It seems that the key and cert are not trusted by your Domain Controller. Sorry, I can't help more without debugging your setup and debugging your setup is out of scope here.

Please, next time, open a separate issue in order to track it more efficiently.

Cheers,

:sunflower:
