### ISSUE TITLE
user.pfx

### ISSUE THREAD

**Issue by sec13b** [AlmondOffSec/PassTheCert#24]
i read all your write , but i didnt see from where is the user.pfx
how i can make user.pfx ?

**Comment by the-useless-one** [comment]
PassTheCert is a tool to authenticate via the SChannel protocol with certificates obtained, legitimately or otherwise, through the Active Directory Certificate Services. I suggest you read [Certified Pre-Owned](https://posts.specterops.io/certified-pre-owned-d95910965cd2), the research this tool is based on, before trying to use the tool for something outside of its purpose.

Please do not open issues if you have trouble with your system configuration, or if you don't understand the attack or how the tool works. Only open issues if the tool bugs or does not work.

Cheers,

Y

**Comment by sec13b** [comment]
Now i understand 
1.Certify 
2.PassTheCert
Thank you
