### ISSUE TITLE
socket ssl wrapping error

### ISSUE THREAD

**Issue by kN6jq** [AlmondOffSec/PassTheCert#7]
it's throw EXCEPTION 
("('socket ssl wrapping error: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:3874)',)",)

![image](https://user-images.githubusercontent.com/27048404/196760383-48bb36c5-7287-49c0-b15f-2d6761e65424.png)

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,
It seems that your Domain Controller uses md5 (or maybe sha1) as signature algorithm for its CA cert. You can confirm this by running `openssl s_client -connect  10.10.1.1:636` on your Kali. 

This problem is related to Python/openssl/your crypto stack, not from our tool, sorry. Maybe you can try to [re-enable](https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level/1233456#1233456) weak protocols but I don't know I never tried it on Kali.

I'm closing this issue but feel free to post a workaround.

:sunflower:

**Comment by helloyw** [comment]
> 弱协议

Have you solved the problem?

**Comment by tucker-clark** [comment]
Just wanted to post that I solved this issue by downgrading to python 3.6
